labelwechatalt/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    url(r'^wechat/', include('wechat.urls')),
    # url(r'^wechat/admin/', admin.site.urls),
]

wechat/urls.py
from django.conf.urls import url
# from django.contrib.auth import views as auth_views

from . import views

app_name = "wechat"
urlpatterns = [
    url(r'^$', views.index, name='index'),
    # url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^label/(?P<article_idx>[0-9]+)/$', views.label, name='label'),
    url(r'^article/(?P<article_idx>[0-9]+)/$', views.show_article, name='article'),
    url(r'^search/$', views.search_candidates, name='search'),
]

wechat/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

wechat/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
# from django.contrib.auth import views as auth_views
from django.apps import apps

import articledata


def index(request):
    # if not request.user.is_authenticated():
    #     return auth_views.login(request, template_name="login.html")
    #
    # context = dict()
    # context['username'] = username = request.user.username
    # num_articles = articledata.get_user_num_articles(username)
    # context['num_articles'] = num_articles
    # #     context['num_mentions'] = reviewdata.get_user_num_labeled_mentions(username)
    # context['label_article_idx'] = 1 if num_articles == 0 else num_articles
    # return render(request, 'wechat/userlabelstat.html', context)
    return HttpResponse('Hi')


def show_article(request, article_idx):
    wechat_config = apps.get_app_config('wechat')
    article_idx = int(article_idx)
    articles = wechat_config.articles

    if article_idx < 1 or article_idx > len(articles):
        return HttpResponse('Article not exist.')

    article = articles[article_idx - 1]
    mentions = wechat_config.article_mentions_dict.get(article['article_id'], None)
    label_results = None

    highlighted_article = articledata.highlight_mentions_para(article['contents'], mentions, label_results)

    context = dict()
    context['username'] = 'dhl'
    context['num_mentions'] = len(mentions)
    context['article_title'] = article['title']
    context['account'] = articledata.get_account_info(wechat_config, article['account_id'])
    context['highlighted_article'] = highlighted_article
    context['user_article_idx'] = article_idx
    context['prev_article_idx'] = article_idx - 1 if article_idx > 1 else 1
    context['next_article_idx'] = article_idx + 1
    context['mention_candidates'] = articledata.get_candidates_of_mentions(wechat_config, mentions)
    return render(request, 'wechat/article.html', context)


def logout(request):
    return HttpResponse('Hi')
    # return auth_views.logout(request, next_page=reverse('wechat:login'))


def label(request, article_idx):
    # tbeg = time()
    articledata.update_label_result(request.user.username, request.POST)
    # return HttpResponse('OK' + rev_idx)
    # print time() - tbeg
    return HttpResponseRedirect(reverse('wechat:article', args=(request.user.username, article_idx,)))


def delete_label(request, user_article_idx, mention_id):
    articledata.delete_label_result(mention_id, request.user.username)
    return HttpResponseRedirect(reverse('wechat:article', args=(request.user.username, user_article_idx,)))


def search_candidates(request):
    mention_id = request.POST['mention_id']
    qstr = request.POST['query_str']
    # reviewed_city = request.POST['reviewed_biz_city']
    wechat_config = apps.get_app_config('wechat')
    candidates = articledata.search_candidates(wechat_config, qstr)
    # print candidates
    context = {
        'mention_id': mention_id,
        'candidates': candidates,
        "candidate_type": "ser"
    }
    return render(request, 'wechat/candidates.html', context)

wechat/templates/wechat/accountdetail.html
{{account.name}}

wechat/templates/wechat/article.html
{% load static %}

<html>
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'wechat/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'wechat/article.css' %}" />
    <script src="{% static 'wechat/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'wechat/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'wechat/js/article.js' %}"></script>
    <title>Title</title>
</head>
<body>

<div class="container">

    <div class="row">
    <div class="div-review-info col-md-6">

        <div class="row">
            <div class="pull-right div-rev-control">
                <a href="{% url 'wechat:article' prev_article_idx %}" class="btn btn-success">Prev Article</a>
                <a href="{% url 'wechat:article' next_article_idx %}" class="btn btn-success">Next Article</a>
            </div>
        </div>

        {% include "wechat/accountdetail.html" %}

        <div class="div-article-title">{{article_title}}</div>

        <div class="div-review-text">
        {{ highlighted_article |safe }}
        </div>
    </div>

    <div class="div-label col-md-6">

        <form id="form-main" action="{% url 'wechat:label' next_article_idx %}" method="post">
        {% csrf_token %}

        <div class="candidates-main">
        {% for mention, is_labeled, candidates, first_candidate_id in mention_candidates %}

            <div class="div-candidates" id="div-mention-{{ forloop.counter }}">

                Mention {{forloop.counter}} / {{num_mentions}}

                {% if is_labeled %}
                    {% include "wechat/labelresult.html" with labelresult=candidates %}
                {% else %}

                <div class="row div-main-label" id="div-main-label-{{ mention.mention_id }}">
                    <div class="col-md-3" id="div-radio-link">
                        <!--<label class="radio-inline" onclick="checkRadio('{{ mention.mention_id }}', 'radio-gen-{{ mention.mention_id }}-1')">-->
                        <label class="radio-inline" onclick="linkChecked('{{ mention.mention_id }}', '{{ first_candidate_id }}')">
                          <input type="radio" id="radio-link-{{ mention.mention_id }}" name="main-label-{{ mention.mention_id }}" value="link"> Link
                        </label>
                    </div>
                    <div class="col-md-3 div-radio-nolink" id="div-radio-unlinkable">
                        <label class="radio-inline" onclick="nolinkChecked('{{ mention.mention_id }}')">
                        <input type="radio" name="main-label-{{ mention.mention_id }}" value="unlinkable" checked="checked"> Unlinkable
                        </label>
                    </div>
                    <div class="col-md-3 div-radio-nolink" id="div-radio-notsure">
                        <label class="radio-inline" onclick="notsureChecked('{{ mention.mention_id }}')">
                        <input type="radio" name="main-label-{{ mention.mention_id }}" value="notsure"> Not Sure
                        </label>
                    </div>
                </div>


                <div id="div-link-{{mention.mention_id}}" class="div-link">
                    <div class="row">
                    <div class="pull-right div-checkbox">
                        <!--<label class="checkbox-inline">-->
                            <!--<input type="checkbox" name="franchise-{{mention.mention_id}}" value="franchise"> Franchise-->
                        <!--</label>-->
                        <label class="checkbox-inline">
                            <input type="checkbox" class="checkbox-wrongspan" name="wrongspan-{{mention.mention_id}}" value="wrongspan"> Wrong Span
                        </label>
                    </div>
                    </div>

                    <ul class="nav nav-tabs">
                      <li class="active"><a data-toggle="tab" href="#gen-{{ mention.mention_id }}">Generated</a></li>
                      <li><a data-toggle="tab" href="#search-{{ mention.mention_id }}">Search</a></li>
                    </ul>

                    <div class="tab-content candidates-tab">
                        <div id="gen-{{ mention.mention_id }}" class="tab-pane fade in active">
                            {% include "wechat/candidates.html" with mention_id=mention.mention_id candidate_type="gen" %}
                        </div>
                        <div id="search-{{ mention.mention_id }}" class="tab-pane fade">
                            {% include "wechat/searchcandidates.html" %}
                        </div>
                    </div>
                </div>

                {% endif %}

            </div>
        {% endfor %}
        </div>
        </form>
    </div>
    </div>
</div>

</body>
</html>

wechat/templates/wechat/candidates.html
{% for acc in candidates %}

<div class="div-candidate-row">
    <div class="div-account-detail"
         onclick="checkRadio('{{mention_id}}', 'radio-{{candidate_type}}-{{ mention_id }}-{{ acc.account_id }}')">
        <div class="div-biz-radio">
            <input type="radio" class="radio-candidate" name="link-label-{{ mention_id }}" value="{{ acc.account_id }}"
                   id="radio-{{candidate_type}}-{{ mention_id }}-{{ acc.account_id }}">
        </div>


        <span class="span-key">Name:</span> <span class="span-value">{{ acc.name }}</span>

    </div>
</div>

{% endfor %}

wechat/templates/wechat/searchcandidates.html
<div class="row div-search-row">
    <div class="col-md-6">
        <input type="text" class="form-control input-md input-search-account" placeholder="Business Name"
               id="input-query-str-{{mention.mention_id}}" value="{{mention.name_str}}"/>
    </div>
    <button class="btn btn-default" type="button" id="btn-search-{{mention.mention_id}}"
            onclick="showSearchResult('{{mention.mention_id}}', '{% url 'wechat:search' %}', '{{csrf_token}}')">
        <!--<i class="glyphicon glyphicon-search"></i>-->
        Search
    </button>
</div>

<div id="search-results-{{mention.mention_id}}">

</div>